export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'AUTH_001',
  EMAIL_ALREADY_EXISTS = 'AUTH_002',
  INVALID_TOKEN = 'AUTH_003',
  TOKEN_EXPIRED = 'AUTH_004',
  UNAUTHORIZED = 'AUTH_005',

  // Profile
  PROFILE_NOT_FOUND = 'PROFILE_001',

  // Health
  METRIC_NOT_FOUND = 'HEALTH_001',

  // Exercise
  EXERCISE_NOT_FOUND = 'EXERCISE_001',
  CANNOT_MODIFY_LIBRARY_EXERCISE = 'EXERCISE_002',

  // Workout
  PLAN_NOT_FOUND = 'WORKOUT_001',
  SESSION_NOT_FOUND = 'WORKOUT_002',
  SESSION_ALREADY_COMPLETED = 'WORKOUT_003',

  // Reminder
  REMINDER_NOT_FOUND = 'REMINDER_001',

  // General
  NOT_FOUND = 'GENERAL_001',
  FORBIDDEN = 'GENERAL_002',
  VALIDATION_ERROR = 'GENERAL_003',
  INTERNAL_ERROR = 'GENERAL_004',
}
